prometheus:
  image: prom/prometheus
  restart: unless-stopped
  ports:
    - 8880:9090
  volumes:
    - ./prometheus:/etc/prometheus
  links:
    - "api"
  
grafana:
  image: grafana/grafana:6.7.3
  restart: unless-stopped
  ports:
    - 8881:3000
  links:
    - "prometheus"

api:
  build: ./app
  dockerfile: Dockerfile
  restart: unless-stopped
  ports:
    - 8882:9991