global:
  scrape_interval: 15s

  external_labels:
    monitor: 'es-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'prom_middleware'
    scrape_interval: 5s
    static_configs:
      - targets: ['api:9991']